if(DEFINED DESTINATION_PARENT AND NOT "${DESTINATION_PARENT}" STREQUAL "")
    string(REGEX REPLACE "/+$" "" clean_destination_parent "${DESTINATION_PARENT}")
    if(IS_SYMLINK "${clean_destination_parent}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E rm -f "${clean_destination_parent}" OUTPUT_QUIET ERROR_QUIET)
    endif()
    file(MAKE_DIRECTORY "${clean_destination_parent}")
endif()

if(DEFINED DESTINATION AND NOT "${DESTINATION}" STREQUAL "")
    string(REGEX REPLACE "/+$" "" clean_destination "${DESTINATION}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E rm -f "${clean_destination}" OUTPUT_QUIET ERROR_QUIET)
    if(IS_DIRECTORY "${clean_destination}")
        file(REMOVE_RECURSE "${clean_destination}")
    endif()
    get_filename_component(destination_parent "${clean_destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${destination_parent}")
endif()
